# Generated by Django 6.1.2 on 2026-10-09 17:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_name', models.CharField(blank=True, max_length=150, verbose_name='rival externo')),
                ('kind', models.CharField(choices=[('official', 'Oficial'), ('tournament', 'Torneo'), ('scrim', 'Scrim'), ('friendly', 'Amistoso')], default='official', max_length=16, verbose_name='tipo')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado'), ('postponed', 'Aplazado')], default='scheduled', max_length=16, verbose_name='estado')),
                ('scheduled_at', models.DateTimeField(verbose_name='fecha y hora')),
                ('tournament_name', models.CharField(blank=True, max_length=150, verbose_name='torneo')),
                ('best_of', models.PositiveSmallIntegerField(default=1, verbose_name='al mejor de')),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='marcador local')),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='marcador visitante')),
                ('notes', models.TextField(blank=True, verbose_name='notas tácticas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='organizations.team', verbose_name='equipo visitante')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='organizations.game', verbose_name='juego')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='organizations.team', verbose_name='equipo local')),
            ],
            options={
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('map_name', models.CharField(max_length=100, verbose_name='mapa')),
                ('home_score', models.PositiveSmallIntegerField(default=0, verbose_name='marcador local')),
                ('away_score', models.PositiveSmallIntegerField(default=0, verbose_name='marcador visitante')),
                ('outcome', models.CharField(blank=True, choices=[('home', 'Local'), ('away', 'Visitante'), ('draw', 'Empate')], max_length=8, verbose_name='resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='matches.match', verbose_name='partido')),
            ],
            options={
                'verbose_name': 'mapa de partido',
                'verbose_name_plural': 'mapas de partido',
                'ordering': ['match', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StatDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('player', 'Jugador'), ('team', 'Equipo')], max_length=8, verbose_name='alcance')),
                ('code', models.SlugField(max_length=60, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='unidad')),
                ('aggregation', models.CharField(choices=[('sum', 'Suma'), ('avg', 'Promedio'), ('max', 'Máximo'), ('min', 'Mínimo'), ('last', 'Último')], default='sum', max_length=8, verbose_name='agregación')),
                ('higher_is_better', models.BooleanField(default=True, verbose_name='mayor es mejor')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_definitions', to='organizations.game', verbose_name='juego')),
            ],
            options={
                'verbose_name': 'definición de estadística',
                'verbose_name_plural': 'definiciones de estadísticas',
                'ordering': ['game', 'scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match', verbose_name='partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_stats', to='players.player', verbose_name='jugador')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_values', to='matches.statdefinition', verbose_name='definición')),
            ],
            options={
                'verbose_name': 'estadística de jugador',
                'verbose_name_plural': 'estadísticas de jugadores',
                'ordering': ['match', 'player', 'definition'],
            },
        ),
        migrations.CreateModel(
            name='TeamMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_values', to='matches.statdefinition', verbose_name='definición')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='matches.match', verbose_name='partido')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_stats', to='organizations.team', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'estadística de equipo',
                'verbose_name_plural': 'estadísticas de equipos',
                'ordering': ['match', 'team', 'definition'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'scheduled_at'], name='matches_mat_status_73a64a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['game', 'scheduled_at'], name='matches_mat_game_id_f52c9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='match_teams_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('away_team__isnull', False), models.Q(('away_name', ''), _negated=True), _connector='OR'), name='match_requires_opponent'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'finished'), _negated=True), models.Q(('home_score__isnull', False), ('away_score__isnull', False)), _connector='OR'), name='finished_match_requires_scores'),
        ),
        migrations.AddConstraint(
            model_name='matchmap',
            constraint=models.UniqueConstraint(fields=('match', 'order'), name='unique_map_order_per_match'),
        ),
        migrations.AddConstraint(
            model_name='statdefinition',
            constraint=models.UniqueConstraint(fields=('game', 'scope', 'code'), name='unique_stat_code_per_game_scope'),
        ),
        migrations.AddIndex(
            model_name='playermatchstat',
            index=models.Index(fields=['player', 'definition'], name='matches_pla_player__815d53_idx'),
        ),
        migrations.AddConstraint(
            model_name='playermatchstat',
            constraint=models.UniqueConstraint(fields=('match', 'player', 'definition'), name='unique_player_stat_per_match'),
        ),
        migrations.AddConstraint(
            model_name='teammatchstat',
            constraint=models.UniqueConstraint(fields=('match', 'team', 'definition'), name='unique_team_stat_per_match'),
        ),
    ]
