# Generated by Django 6.1.2 on 2026-10-09 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='país')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'integrante del staff',
                'verbose_name_plural': 'integrantes del staff',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_coach', 'Entrenador principal'), ('assistant_coach', 'Entrenador asistente'), ('analyst', 'Analista'), ('manager', 'Manager'), ('performance', 'Preparador de rendimiento'), ('other', 'Otro')], max_length=32, verbose_name='rol')),
                ('responsibilities', models.TextField(blank=True, verbose_name='responsabilidades')),
                ('started_at', models.DateField(verbose_name='fecha de inicio')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='staff.staffmember', verbose_name='integrante del staff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='organizations.team', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'asignación de staff',
                'verbose_name_plural': 'asignaciones de staff',
                'ordering': ['team', '-started_at'],
                'indexes': [models.Index(fields=['team', 'role'], name='staff_teams_team_id_2d6d5a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('staff', 'team', 'role'), name='unique_open_staff_assignment'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='staff_assignment_end_not_before_start')],
            },
        ),
    ]
