# Generated by Django 6.1.2 on 2026-10-09 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='abreviatura')),
                ('default_team_size', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='jugadores por equipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'juego competitivo',
                'verbose_name_plural': 'juegos competitivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('abbreviation', models.CharField(blank=True, max_length=20, verbose_name='abreviatura')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='país')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='fecha de fundación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('abbreviation', models.CharField(blank=True, max_length=10, verbose_name='abreviatura')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.game', verbose_name='juego')),
            ],
            options={
                'verbose_name': 'rol de juego',
                'verbose_name_plural': 'roles de juego',
                'ordering': ['game', 'name'],
                'constraints': [models.UniqueConstraint(fields=('game', 'name'), name='unique_game_role_name')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=150, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'En pausa'), ('inactive', 'Inactivo'), ('disbanded', 'Disuelto')], default='active', max_length=16, verbose_name='estado')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='fecha de fundación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.game', verbose_name='juego')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizations.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['organization', 'game', 'name'],
                'indexes': [models.Index(fields=['game', 'status'], name='organizatio_game_id_d40091_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'slug'), name='unique_team_slug_per_org'), models.UniqueConstraint(fields=('organization', 'game', 'name'), name='unique_team_name_per_org_game')],
            },
        ),
    ]
