# Generated by Django 6.1.2 on 2026-10-09 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='apellidos')),
                ('nickname', models.CharField(max_length=60, unique=True, verbose_name='nickname')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='país')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'jugador',
                'verbose_name_plural': 'jugadores',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dorsal')),
                ('joined_at', models.DateField(verbose_name='fecha de incorporación')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='fecha de salida')),
                ('status', models.CharField(choices=[('active', 'Titular'), ('bench', 'Suplente'), ('inactive', 'Inactivo'), ('left', 'Baja')], default='active', max_length=16, verbose_name='estado')),
                ('is_captain', models.BooleanField(default=False, verbose_name='capitán')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('competitive_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_assignments', to='organizations.gamerole', verbose_name='rol competitivo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='players.player', verbose_name='jugador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_assignments', to='organizations.team', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'asignación de jugador',
                'verbose_name_plural': 'asignaciones de jugadores',
                'ordering': ['team', '-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='players_pla_last_na_1786cf_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamassignment',
            index=models.Index(fields=['player', 'status'], name='players_pla_player__c66be5_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamassignment',
            index=models.Index(fields=['team', 'status'], name='players_pla_team_id_d55604_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerteamassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('player', 'team'), name='unique_open_assignment_per_player_team'),
        ),
        migrations.AddConstraint(
            model_name='playerteamassignment',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='assignment_left_not_before_joined'),
        ),
    ]
