# Generated by Django 6.1.2 on 2026-10-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('scheduled_at', models.DateTimeField(verbose_name='fecha y hora')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duración (minutos)')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='ubicación')),
                ('objectives', models.TextField(blank=True, verbose_name='objetivos')),
                ('plan', models.TextField(blank=True, verbose_name='planificación')),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='planned', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='organizations.team', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'sesión de entrenamiento',
                'verbose_name_plural': 'sesiones de entrenamiento',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('late', 'Tarde'), ('absent', 'Ausente'), ('excused', 'Justificado')], default='present', max_length=10, verbose_name='asistencia')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance', to='players.player', verbose_name='jugador')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='training.trainingsession', verbose_name='sesión')),
            ],
            options={
                'verbose_name': 'asistencia a entrenamiento',
                'verbose_name_plural': 'asistencias a entrenamiento',
                'ordering': ['session', 'player'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['team', 'scheduled_at'], name='training_tr_team_id_03a9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['status'], name='training_tr_status_f37730_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingattendance',
            constraint=models.UniqueConstraint(fields=('session', 'player'), name='unique_attendance_per_session'),
        ),
    ]
